before_script:
   - nproc=`grep -c '^processor' /proc/cpuinfo`
   - echo "nproc = ${nproc}"
   - mkdir -p build; cd build/

stages:
  - build
  - test

build:
  stage: build
  script:
    - cmake .. -DRTYPE_TESTS=ON
    - make -j${nproc}
  artifacts:
    untracked: true
    - build/

unit-tests:
  stage: test
  dependencies:
    - build
  script:
    - ctest . --output-on-failure