stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DRTYPE_TESTS=ON
    - make -j 4

unit-tests:
  stage: test
  script:
    - cd build
    - ctest . --output-on-failure